# Linear Algebra
<article class="message is-info">
  <div class="message-header">Overview</div>
  <div class="message-body">
  
  This exercise is a continuation of week 3 exercise Basic Linear Algebra in Python
. It introduces how to solve linear systems of equations using linear algebra. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.

  
  </div>
</article>


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#inverses">Task 1: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 2: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 3: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 4: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 5: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 6: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 7: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [17]:
import numpy as np
import matplotlib.pyplot as plt

# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

<article class="message task"><a class="anchor" id="inverses"></a>
    <div class="message-header">
        <span>Task 1: Inverses</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          
          
          
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">

  The question relates to the limitations of floating point numbers.


  </div>
</article>


</div></article>



In [18]:
A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)

A_inv
C_inv

array([[   -72.,   -225.,    525.,     42.],
       [  1260.,   3675.,  -8820.,   -630.],
       [ -3696., -10710.,  25830.,   1764.],
       [  2700.,   7830., -18900.,  -1260.]])

In [19]:
np.abs(np.round(A @ A_inv))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Properties
<article class="message task"><a class="anchor" id="inverse_prop"></a>
    <div class="message-header">
        <span>Task 2: Inverse properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          
          
          
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$



</div></article>



In [20]:
print(np.round(D_inv @ E_inv, decimals=5))
print("\n")
print(np.round(np.linalg.inv(E @ D), decimals=5))

[[ 0.25261  0.13579 -0.51302]
 [-0.08601  0.11462  0.1854 ]
 [ 0.16593 -0.18963  0.17778]]


[[ 0.25261  0.13579 -0.51302]
 [-0.08601  0.11462  0.1854 ]
 [ 0.16593 -0.18963  0.17778]]


In [21]:
np.round(D_inv @ E_inv, decimals=5) == np.round(np.linalg.inv(E @ D), decimals=5)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
np.round(D_inv @ E_inv, decimals=5) == np.round(np.linalg.inv(D @ E), decimals=5)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [23]:
print(np.round(D_inv @ E_inv, decimals=5))
print("\n")
print(np.round(np.linalg.inv(D @ E), decimals=5))

[[ 0.25261  0.13579 -0.51302]
 [-0.08601  0.11462  0.1854 ]
 [ 0.16593 -0.18963  0.17778]]


[[ 0.21096 -0.256   -0.1517 ]
 [-0.15365  0.20571  0.56635]
 [ 0.05367 -0.28343  0.12834]]


<article class="message task"><a class="anchor" id="determinant"></a>
    <div class="message-header">
        <span>Task 3: The determinant</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          
          
          
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).



</div></article>



In [24]:
a_det = np.linalg.det(A)
b_det = np.linalg.det(B)
c_det = np.linalg.det(C)
print("determinant of B:", b_det)
print(np.round(a_det, decimals=9), np.round(b_det, decimals=9), np.round(c_det, decimals=9))

determinant of B: 2.7733391199176e-32
1.65e-07 0.0 1.05e-07


In [25]:
print(B)
B_inv = np.linalg.inv(B)
B_inv

[[-16  15 -14  13]
 [-12  11 -10   9]
 [ -8   7  -6   5]
 [ -4   3  -2   1]]


array([[-3.00239975e+16,  4.80383960e+16, -6.00479950e+15,
        -1.20095990e+16],
       [-4.80383960e+16,  7.20575940e+16, -0.00000000e+00,
        -2.40191980e+16],
       [-6.00479950e+15,  0.00000000e+00,  1.80143985e+16,
        -1.20095990e+16],
       [ 1.20095990e+16, -2.40191980e+16,  1.20095990e+16,
        -0.00000000e+00]])

<article class="message task"><a class="anchor" id="transpose"></a>
    <div class="message-header">
        <span>Task 4: Transpose</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          
          
          
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.

  
  </div>
</article>



</div></article>



In [26]:
D_inv_tra = np.linalg.inv(D.T)
D_tra_inv = np.linalg.inv(D).T

print(D_inv_tra)
print('\n')
print(D_tra_inv)

[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ the vector of unknowns, and $b$ is the vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$
<article class="message task"><a class="anchor" id="eqsys"></a>
    <div class="message-header">
        <span>Task 5: Solving linear equation systems</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          
          
          
          <i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


</div></article>



In [27]:
A = np.array([[2, 3],[1, 1]])
b = np.array([-1, 0])

np.linalg.solve(A,b)

array([ 1., -1.])

In [28]:
A = np.array([[1,0],[0,1]])
b = np.array([5,7])

np.linalg.solve(A,b)

array([5., 7.])

In [29]:
A = np.array([[0,1],[-2,-3]])
b = np.array([-1,2])

np.linalg.solve(A,b)

array([ 0.5, -1. ])

In [30]:
A = np.array([[1,-3,3],[1,-5,3],[6,-6,4]])
b = np.array([0.5,0.5,1])

np.linalg.solve(A,b)

array([7.14285714e-02, 7.59974094e-18, 1.42857143e-01])

## Matrix multiplication (optional)
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is an $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.
<article class="message task"><a class="anchor" id="matmul"></a>
    <div class="message-header">
        <span>Task 6: Implementing matrix multiplication</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i>
          
          
          
          <i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.
<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  It might be helpful to calculate the correct result by hand first, to make debugging easier.

  
  </div>
</article>



</div></article>



In [ ]:
import numpy as np

def matmul(a, b):
    bT = matrixTranspose(b)
    mr_rows = len(a)
    mr_cols = len(b[0])
    mr = np.zeros((mr_rows, mr_cols))
    for rowA in range(mr_rows):
        for rowB in range(mr_rows):
            dprod = 0
            for col in range(mr_cols):
                dprod += a[rowA][col] * bT[rowB][col]
            mr[rowA][rowB] = dprod
    return mr

def matrixTranspose(a):
    aT = np.zeros_like(a)
    for col in range(len(a[0])):            # for each column in b
        for row in range(len(a)):           # access each row
            aT[col][row] = a[row][col]      # flip the matrix
    return aT

#-------------------------------

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

result = matmul(ma, mb)

print("My method:\n", result)
print("Numpy:\n", np.array(ma) @ np.array(mb))

My method:
 [[ 33.   6.  26.]
 [ 78.  21.  77.]
 [123.  36. 128.]]
Numpy:
 [[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]


<article class="message task"><a class="anchor" id="extra"></a>
    <div class="message-header">
        <span>Task 7: Extra exercises</span>
        <span class="has-text-right">
          
          
          <i class="bi bi-lightbulb-fill"></i>
          
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)




</div></article>

